[package]
name = "day22"
version = "0.1.0"
authors = ["bobismijnnaam <bobrubbens@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.8.2"
nalgebra = "0.19.0"
